# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0003_auto_20180201_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slicksliderimage',
            options={'ordering': ['order'], 'verbose_name': 'slider image', 'verbose_name_plural': 'slider images'},
        ),
        migrations.AddField(
            model_name='slicksliderimage',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Image order'),
        ),
    ]
