# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0004_auto_20180906_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slicksliderimage',
            options={'ordering': ['position'], 'verbose_name': 'slider image', 'verbose_name_plural': 'slider images'},
        ),
        migrations.RenameField(
            model_name='slicksliderimage',
            old_name='order',
            new_name='position',
        ),
    ]
