# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_slick_slider', '0006_auto_20180906_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slicksliderimage',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='image link'),
        ),
    ]
